default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['MY_APP_DATABASE_URL'] %>
  port: 5432
  pool: 5
  variables:
    statement_timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: airbnb_test

production:
  <<: *default